<?xml version="1.0" encoding="UTF-8"?>
<!--
	Ensures consistent language metadata by remapping language fields
	not containing ISO 639-2/B codes to the language-invalid field.

	Valid language codes are those we have display strings for.
	Based on the MARC list + a few deprecated and extra ones:
	https://docs.google.com/spreadsheets/d/1b2iXB4AEdc2gyS4cbFWtRg-_gUP0eh9Xjp3lXX_pRQA/edit
	with zzz, zxx, mul, mis removed.

	Requires EXSLT.

	2014 Sven-S. Porst <ssp-web@earthlingsoft.net>
-->

<xsl:stylesheet
		version="1.0"
		xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
		xmlns:pz="http://www.indexdata.com/pazpar2/1.0"
		xmlns:exsl="http://exslt.org/common"
		extension-element-prefixes="exsl">

	<xsl:output indent="yes" method="xml" version="1.0" encoding="UTF-8"/>


	<xsl:template match="@*|node()">
		<xsl:copy>
			<xsl:apply-templates select="@*|node()"/>
		</xsl:copy>
	</xsl:template>



	<!--
		Change the type of language fields without a known code to language-invalid.
		If no language field remains, add one with »zzz« for unknown.
	-->
	<xsl:template match="pz:metadata[@type='language']">
		<xsl:variable name="languages">
			<xsl:choose>
				<xsl:when test="
					.='aar' or
					.='abk' or
					.='ace' or
					.='ach' or
					.='ada' or
					.='ady' or
					.='afa' or
					.='afh' or
					.='afr' or
					.='ain' or
					.='aka' or
					.='akk' or
					.='alb' or
					.='ale' or
					.='alg' or
					.='alt' or
					.='amh' or
					.='ang' or
					.='anp' or
					.='apa' or
					.='ara' or
					.='arc' or
					.='arg' or
					.='arm' or
					.='arn' or
					.='arp' or
					.='art' or
					.='arw' or
					.='asm' or
					.='ast' or
					.='ath' or
					.='aus' or
					.='ava' or
					.='ave' or
					.='awa' or
					.='aym' or
					.='aze' or
					.='bad' or
					.='bai' or
					.='bak' or
					.='bal' or
					.='bam' or
					.='ban' or
					.='baq' or
					.='bas' or
					.='bat' or
					.='bej' or
					.='bel' or
					.='bem' or
					.='ben' or
					.='ber' or
					.='bho' or
					.='bih' or
					.='bik' or
					.='bin' or
					.='bis' or
					.='bla' or
					.='bnt' or
					.='bos' or
					.='bra' or
					.='bre' or
					.='btk' or
					.='bua' or
					.='bug' or
					.='bul' or
					.='bur' or
					.='byn' or
					.='cad' or
					.='cai' or
					.='car' or
					.='cat' or
					.='cau' or
					.='ceb' or
					.='cel' or
					.='cha' or
					.='chb' or
					.='che' or
					.='chg' or
					.='chi' or
					.='chk' or
					.='chm' or
					.='chn' or
					.='cho' or
					.='chp' or
					.='chr' or
					.='chu' or
					.='chv' or
					.='chy' or
					.='cmc' or
					.='cop' or
					.='cor' or
					.='cos' or
					.='cpe' or
					.='cpf' or
					.='cpp' or
					.='cre' or
					.='crh' or
					.='crp' or
					.='csb' or
					.='cus' or
					.='cze' or
					.='dak' or
					.='dan' or
					.='dar' or
					.='day' or
					.='del' or
					.='den' or
					.='dgr' or
					.='din' or
					.='div' or
					.='doi' or
					.='dra' or
					.='dsb' or
					.='dua' or
					.='dum' or
					.='dut' or
					.='dyu' or
					.='dzo' or
					.='efi' or
					.='egy' or
					.='eka' or
					.='elx' or
					.='eng' or
					.='enm' or
					.='epo' or
					.='est' or
					.='ewe' or
					.='ewo' or
					.='fan' or
					.='fao' or
					.='fat' or
					.='fij' or
					.='fil' or
					.='fin' or
					.='fiu' or
					.='fon' or
					.='fre' or
					.='frm' or
					.='fro' or
					.='frr' or
					.='frs' or
					.='fry' or
					.='ful' or
					.='fur' or
					.='gaa' or
					.='gay' or
					.='gba' or
					.='gem' or
					.='geo' or
					.='ger' or
					.='gez' or
					.='gil' or
					.='gla' or
					.='gle' or
					.='glg' or
					.='glv' or
					.='gmh' or
					.='goh' or
					.='gon' or
					.='gor' or
					.='got' or
					.='grb' or
					.='grc' or
					.='gre' or
					.='grn' or
					.='gsw' or
					.='guj' or
					.='gwi' or
					.='hai' or
					.='hat' or
					.='hau' or
					.='haw' or
					.='heb' or
					.='her' or
					.='hil' or
					.='him' or
					.='hin' or
					.='hit' or
					.='hmn' or
					.='hmo' or
					.='hrv' or
					.='hsb' or
					.='hun' or
					.='hup' or
					.='iba' or
					.='ibo' or
					.='ice' or
					.='ido' or
					.='iii' or
					.='ijo' or
					.='iku' or
					.='ile' or
					.='ilo' or
					.='ina' or
					.='inc' or
					.='ind' or
					.='ine' or
					.='inh' or
					.='ipk' or
					.='ira' or
					.='iro' or
					.='ita' or
					.='jav' or
					.='jbo' or
					.='jpn' or
					.='jpr' or
					.='jrb' or
					.='kaa' or
					.='kab' or
					.='kac' or
					.='kal' or
					.='kam' or
					.='kan' or
					.='kar' or
					.='kas' or
					.='kau' or
					.='kaw' or
					.='kaz' or
					.='kbd' or
					.='kha' or
					.='khi' or
					.='khm' or
					.='kho' or
					.='kik' or
					.='kin' or
					.='kir' or
					.='kmb' or
					.='kok' or
					.='kom' or
					.='kon' or
					.='kor' or
					.='kos' or
					.='kpe' or
					.='krc' or
					.='krl' or
					.='kro' or
					.='kru' or
					.='kua' or
					.='kum' or
					.='kur' or
					.='kut' or
					.='lad' or
					.='lah' or
					.='lam' or
					.='lao' or
					.='lat' or
					.='lav' or
					.='lez' or
					.='lim' or
					.='lin' or
					.='lit' or
					.='lol' or
					.='loz' or
					.='ltz' or
					.='lua' or
					.='lub' or
					.='lug' or
					.='lui' or
					.='lun' or
					.='luo' or
					.='lus' or
					.='mac' or
					.='mad' or
					.='mag' or
					.='mah' or
					.='mai' or
					.='mak' or
					.='mal' or
					.='man' or
					.='mao' or
					.='map' or
					.='mar' or
					.='mas' or
					.='may' or
					.='mdf' or
					.='mdr' or
					.='men' or
					.='mga' or
					.='mic' or
					.='min' or
					.='mkh' or
					.='mlg' or
					.='mlt' or
					.='mnc' or
					.='mni' or
					.='mno' or
					.='moh' or
					.='mon' or
					.='mos' or
					.='mun' or
					.='mus' or
					.='mwl' or
					.='mwr' or
					.='myn' or
					.='myv' or
					.='nah' or
					.='nai' or
					.='nap' or
					.='nau' or
					.='nav' or
					.='nbl' or
					.='nde' or
					.='ndo' or
					.='nds' or
					.='nep' or
					.='new' or
					.='nia' or
					.='nic' or
					.='niu' or
					.='nno' or
					.='nob' or
					.='nog' or
					.='non' or
					.='nor' or
					.='nqo' or
					.='nso' or
					.='nub' or
					.='nwc' or
					.='nya' or
					.='nym' or
					.='nyn' or
					.='nyo' or
					.='nzi' or
					.='oci' or
					.='oji' or
					.='ori' or
					.='orm' or
					.='osa' or
					.='oss' or
					.='ota' or
					.='oto' or
					.='paa' or
					.='pag' or
					.='pal' or
					.='pam' or
					.='pan' or
					.='pap' or
					.='pau' or
					.='peo' or
					.='per' or
					.='phi' or
					.='phn' or
					.='pli' or
					.='pol' or
					.='pon' or
					.='por' or
					.='pra' or
					.='pro' or
					.='pus' or
					.='que' or
					.='raj' or
					.='rap' or
					.='rar' or
					.='roa' or
					.='roh' or
					.='rom' or
					.='rum' or
					.='run' or
					.='rup' or
					.='rus' or
					.='sad' or
					.='sag' or
					.='sah' or
					.='sai' or
					.='sal' or
					.='sam' or
					.='san' or
					.='sas' or
					.='sat' or
					.='scn' or
					.='sco' or
					.='sel' or
					.='sem' or
					.='sga' or
					.='sgn' or
					.='shn' or
					.='sid' or
					.='sin' or
					.='sio' or
					.='sit' or
					.='sla' or
					.='slo' or
					.='slv' or
					.='sma' or
					.='sme' or
					.='smi' or
					.='smj' or
					.='smn' or
					.='smo' or
					.='sms' or
					.='sna' or
					.='snd' or
					.='snk' or
					.='sog' or
					.='som' or
					.='son' or
					.='sot' or
					.='spa' or
					.='srd' or
					.='srn' or
					.='srp' or
					.='srr' or
					.='ssa' or
					.='ssw' or
					.='suk' or
					.='sun' or
					.='sus' or
					.='sux' or
					.='swa' or
					.='swe' or
					.='syc' or
					.='syr' or
					.='tah' or
					.='tai' or
					.='tam' or
					.='tat' or
					.='tel' or
					.='tem' or
					.='ter' or
					.='tet' or
					.='tgk' or
					.='tgl' or
					.='tha' or
					.='tib' or
					.='tig' or
					.='tir' or
					.='tiv' or
					.='tkl' or
					.='tlh' or
					.='tli' or
					.='tmh' or
					.='tog' or
					.='ton' or
					.='tpi' or
					.='tsi' or
					.='tsn' or
					.='tso' or
					.='tuk' or
					.='tum' or
					.='tup' or
					.='tur' or
					.='tut' or
					.='tvl' or
					.='twi' or
					.='tyv' or
					.='udm' or
					.='uga' or
					.='uig' or
					.='ukr' or
					.='umb' or
					.='und' or
					.='urd' or
					.='uzb' or
					.='vai' or
					.='ven' or
					.='vie' or
					.='vol' or
					.='vot' or
					.='wak' or
					.='wal' or
					.='war' or
					.='was' or
					.='wel' or
					.='wen' or
					.='wln' or
					.='wol' or
					.='xal' or
					.='xho' or
					.='yao' or
					.='yap' or
					.='yid' or
					.='yor' or
					.='ypk' or
					.='zap' or
					.='zbl' or
					.='zen' or
					.='zha' or
					.='znd' or
					.='zul' or
					.='zun' or
					.='zza' or
					.='esp' or
					.='eth' or
					.='far' or
					.='fri' or
					.='gag' or
					.='iri' or
					.='esk' or
					.='cam' or
					.='max' or
					.='mol' or
					.='lan' or
					.='gal' or
					.='lap' or
					.='gae' or
					.='scc' or
					.='scr' or
					.='sho' or
					.='snh' or
					.='sso' or
					.='swz' or
					.='tag' or
					.='taj' or
					.='tar' or
					.='tsw'
				">
				<xsl:copy-of select="."/>
				</xsl:when>
				<xsl:otherwise>
					<pz:metadata type="language-invalid">
						<xsl:value-of select="."/>
					</pz:metadata>
				</xsl:otherwise>
			</xsl:choose>
		</xsl:variable>
		
		<xsl:copy-of select="$languages"/>
		
		<xsl:choose>
			<xsl:when test="function-available('exsl:node-set')">
				<xsl:message>gaga</xsl:message>
				<xsl:if test="count(exsl:node-set($languages)/pz:metadata[@type='language']) = 0">
					<pz:metadata type="language">zzz</pz:metadata>
				</xsl:if>
			</xsl:when>
			<xsl:otherwise>
				<xsl:message>WARNING: No EXSLT support. Unknown language handling may be incorrect.</xsl:message>
		   </xsl:otherwise>
		</xsl:choose>
	</xsl:template>

</xsl:stylesheet>
